# Generated by Django 3.2.4 on 2024-07-02 11:05

from django.db import migrations, models
import tags.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[tags.models.validate_tag_name])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
