# Generated by Django 5.0.6 on 2024-06-27 09:50

import tags.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[tags.models.validate_tag_name])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
